auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Xinxin Liu
url: http://xinxin-liu.github.io/
feed: /atom.xml
author_info: <a href="http://xinxin-liu.github.io/">Xinxin Liu</a>
